version: '3.0'

services:
   nginx:
        image: nginx
        ports:
          - 8080:80
        volumes:
          - /home:/etc/nginx
        links:
          - mysql
   mysql:
        image: mysql

